remote_theme: chrisrhymes/bulma-clean-theme@v0.13.2

title: 8Rivers
description: Welcome to 8Rivers homepage.
defaults:
  - scope:
      path: ""
    values:
      hero_image: /assets/img/top-banner.jpg
