remote_theme: chrisrhymes/bulma-clean-theme@v0.13.2

title: 8Rivers
defaults:
  - scope:
      path: ""
    values:
      title: 8Rivers
      subtitle: Mohammad Masoumi
      hero_image: /assets/img/top-banner.jpg
      hero_darken: true
